import streamlit as st
import streamlit.components.v1 as components

st.set_page_config(page_title="Microsoft 365 体験トレーニング", layout="wide", initial_sidebar_state="collapsed")

st.markdown("""
<style>
[data-testid="stSidebar"], [data-testid="collapsedControl"] {display:none !important;}
[data-testid="stHeader"] {display:none !important;}
.block-container {padding: 0 !important; max-width: 100% !important;}
html, body, .stApp {background:#eef3fb; overflow-x:hidden;}
iframe {border:0 !important; display:block;}
</style>
""", unsafe_allow_html=True)

APP_HTML = r'''
<!doctype html>
<html lang="ja">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<style>
:root{--blue:#185abd;--blue2:#2563d6;--line:#cfd8e6;--bg:#eef3fb;--panel:#fff;--ink:#0f1b2d;--muted:#5c6678;--light:#f6f8fb;--teal:#03787c;--purple:#6264a7;}
*{box-sizing:border-box} html,body{margin:0;padding:0;overflow:hidden;background:var(--bg);font-family:"Segoe UI",system-ui,-apple-system,BlinkMacSystemFont,"Noto Sans JP",sans-serif;color:var(--ink)}
#app{height:748px;max-height:748px;overflow:hidden;padding:10px 14px 8px;}
.header{height:44px;display:flex;align-items:center;justify-content:space-between;gap:16px}
.header h1{font-size:24px;line-height:1;margin:0;font-weight:750;letter-spacing:.01em}.hint{font-size:13px;color:var(--muted)}
.service-tabs{height:44px;display:grid;grid-template-columns:repeat(6,1fr);gap:10px;margin-bottom:8px}.service-tab{border:1px solid #b9c9df;background:#fff;border-radius:8px;display:flex;align-items:center;justify-content:center;font-weight:650;cursor:pointer;height:38px}.service-tab.active{background:#2f64d6;color:#fff;border-color:#2f64d6;box-shadow:0 3px 8px rgba(47,100,214,.18)}
.progress{height:44px;border:1px solid #a9c8ff;background:#edf5ff;border-radius:10px;display:flex;align-items:center;justify-content:space-between;padding:0 16px;margin-bottom:8px;font-size:15px}.progress b{color:#0054c7}.done{font-weight:750;color:#0054c7}
.shell{height:528px;border:1px solid #c7d2e3;border-radius:10px;background:#fff;overflow:hidden;box-shadow:0 8px 18px rgba(17,33,62,.08)}
.appbar{height:45px;background:var(--blue);color:#fff;display:flex;align-items:center;justify-content:space-between;padding:0 18px;font-weight:750}.appbar .title{font-size:21px}.appbar .actions{display:flex;gap:16px;font-size:13px;opacity:.95}.tabs{height:38px;display:flex;border-bottom:1px solid var(--line);background:#fff}.tab{min-width:102px;padding:9px 16px;text-align:center;font-weight:650;cursor:pointer;border-right:1px solid transparent}.tab.active{background:#edf4ff;color:#064fb3;border:1px solid #b8cff4;border-bottom:none;border-radius:6px 6px 0 0;margin:5px 0 0 8px;padding-top:6px;height:33px}.ribbon{height:70px;background:#fbfcff;border-bottom:1px solid var(--line);display:flex;align-items:center;gap:10px;padding:10px 16px}.btn,.select,.input{border:1px solid #b9c9df;background:#fff;border-radius:7px;height:34px;padding:0 12px;font:inherit;font-weight:600;color:#0f274a}.btn{cursor:pointer}.btn:hover{background:#edf5ff}.btn.active{background:#dceaff;border-color:#7aa7e8}.select{min-width:108px}.input{font-weight:400}.sep{height:40px;width:1px;background:#cfd8e6;margin:0 4px}
.work{height:375px;background:#e8eef8;display:grid;grid-template-columns:1fr 265px;gap:16px;padding:14px 20px}.page{width:650px;max-width:100%;height:330px;background:white;margin:0 auto;border:1px solid #d3d6dc;box-shadow:0 8px 25px rgba(27,48,80,.1);padding:52px 72px;font-size:16px;line-height:1.65;outline:none;overflow:hidden}.page h2{font-size:19px;margin:0 0 12px}.page ul{margin:6px 0 0 1.2em;padding:0}.status-card{height:330px;background:#fff;border:1px solid #dbe3ef;border-radius:10px;padding:14px 16px;overflow:hidden}.status-card h3{margin:0 0 12px;font-size:17px}.row{display:flex;justify-content:space-between;border-bottom:1px solid #edf1f6;padding:7px 0}.note{background:#f0f6ff;border-left:4px solid #1f64d3;margin-top:10px;padding:9px;font-size:13px;line-height:1.5}.footer{height:26px;background:#f7f9fc;border-top:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;padding:0 18px;font-size:12px;color:#536174}
.grid{display:grid;gap:1px;background:#b7c5d9;border:1px solid #b7c5d9}.grid4{grid-template-columns:80px repeat(4,1fr)}.cell,.head{background:#fff;min-height:34px;padding:7px;text-align:center}.head{background:#edf2f8;font-weight:700}.cell.sel{outline:2px solid #217346;background:#ebfff2}.formula{height:35px;background:#fff;border-bottom:1px solid var(--line);display:flex;align-items:center;gap:8px;padding:0 16px}.fx{font-weight:700;color:#217346}.chart{height:128px;display:flex;align-items:end;gap:18px;padding:18px;background:#fff;border:1px solid #dce5f0;border-radius:8px}.bar{width:52px;background:#3b73d9;border-radius:5px 5px 0 0}.team-layout{height:445px;display:grid;grid-template-columns:210px 1fr 260px;background:#f3f5f9}.rail{border-right:1px solid var(--line);padding:12px}.channel{padding:9px;border-radius:6px;margin:5px 0}.channel.active{background:#e7ebf8;color:#464775;font-weight:700}.chat{padding:14px;display:flex;flex-direction:column;gap:8px}.message{background:#fff;border:1px solid #dbe3ef;border-radius:8px;padding:8px 10px}.compose{margin-top:auto;display:flex;gap:8px}.side{border-left:1px solid var(--line);background:#fff;padding:12px}.file-list{display:grid;grid-template-columns:260px 1fr 260px;height:445px;background:#f5f8fc}.leftnav{background:#fff;border-right:1px solid var(--line);padding:12px}.mainlist{padding:14px}.file-row{display:grid;grid-template-columns:1fr 120px 120px;gap:8px;background:#fff;border:1px solid #dbe3ef;border-radius:7px;padding:9px 10px;margin-bottom:8px;cursor:pointer}.file-row.active{outline:2px solid #1b66d1;background:#eef5ff}.details{background:#fff;border-left:1px solid var(--line);padding:14px}.site-top{display:flex;gap:10px;margin-bottom:12px}.news{background:#fff;border:1px solid #dbe3ef;border-radius:8px;padding:10px;margin-top:10px}.copilot{height:445px;background:#f4f7fb;display:grid;grid-template-columns:1fr 330px;gap:16px;padding:16px}.prompt{background:#fff;border:1px solid #dbe3ef;border-radius:10px;padding:14px}.textarea{width:100%;height:92px;border:1px solid #b9c9df;border-radius:8px;padding:10px;font:inherit;resize:none}.answer{background:#fff;border:1px solid #dbe3ef;border-radius:10px;padding:14px;line-height:1.55}.links{height:56px;display:flex;align-items:center;gap:10px;margin-top:6px}.links span{font-weight:750;margin-right:4px}.links a{border:1px solid #b9c9df;border-radius:7px;background:#fff;padding:8px 16px;text-decoration:none;color:#12325c;font-weight:650}.links a:hover{background:#edf5ff}
@media(max-width:1200px){#app{height:720px}.shell{height:510px}.work{grid-template-columns:1fr 230px;padding:12px}.page{padding:42px 54px}.service-tabs{gap:7px}.tab{min-width:90px}.ribbon{gap:6px}.btn{padding:0 9px}}
</style>
</head>
<body>
<div id="app">
  <div class="header"><h1>Microsoft 365 体験トレーニング</h1><div class="hint">M365風UI上で操作し、画面の変化を確認します</div></div>
  <div class="service-tabs" id="serviceTabs"></div>
  <div class="progress"><div><b>体験：</b><span id="taskText">白紙ページの本文を編集</span></div><div class="done"><span id="doneCount">0</span>/<span id="totalCount">9</span> 完了</div></div>
  <div class="shell" id="shell"></div>
  <div class="links"><span>実サービス</span><a target="_blank" href="https://word.cloud.microsoft/">Word</a><a target="_blank" href="https://excel.cloud.microsoft/">Excel</a><a target="_blank" href="https://teams.microsoft.com/">Teams</a><a target="_blank" href="https://onedrive.live.com/">OneDrive</a><a target="_blank" href="https://www.microsoft365.com/launch/sharepoint">SharePoint</a><a target="_blank" href="https://copilot.microsoft.com/">Copilot</a></div>
</div>
<script>
const state={svc:'Word', wordTab:'ホーム', done:{Word:new Set(),Excel:new Set(),Teams:new Set(),OneDrive:new Set(),SharePoint:new Set(),Copilot:new Set()}, word:{bold:false,underline:false,bullets:false,style:'標準',saved:'未保存',share:'未共有',comments:0,zoom:'100%',bg:'#fff',border:false,margin:'標準',mail:false,table:false,text:'<h2>M365移行後のファイル保存ルール</h2><p>旧Officeでは個人PCや共有フォルダーに保存していました。</p><p>Microsoft 365移行後は、OneDriveとSharePointを使い分け、Teamsから関係者へ共有します。</p>'}, excel:{formula:'=SUM(B2:B4)',result:'未計算',selected:'B5',protected:false,chart:false}, teams:{sent:false,mention:false,file:false,reaction:false,meeting:false}, od:{selected:'研修資料.docx',shared:false,sync:'同期済み',uploaded:false,version:'最新版'}, sp:{site:'総務部サイト',added:false,perm:false,news:false}, cop:{prompt:'研修資料の要点を3つに要約してください。',answer:'プロンプトを入力して実行してください。'}};
const tasks={Word:['白紙ページの本文を編集','ホームで文字書式を選ぶ','挿入で表を入れる','レイアウトで余白を変える','デザインで背景または罫線を変える','校閲でコメントを追加','表示で倍率を変える','差し込み文書を挿入','保存または共有を確認'],Excel:['セルを選択','数式バーに =SUM(B2:B4) を入力','計算する','グラフを挿入','シートを保護'],Teams:['@メンションを入れて送信','ファイルを共有','リアクションする','会議を開始'],OneDrive:['ファイルを選択','ファイルをアップロード','共有リンクを作成','同期状態を確認','バージョン履歴から復元'],SharePoint:['サイトを選択','ドキュメントを追加','権限を確認','ニュースを投稿'],Copilot:['プロンプトを入力','要約を作成','文章を整える','次の操作を提案']};
const services=['Word','Excel','Teams','OneDrive','SharePoint','Copilot'];
function mark(key){state.done[state.svc].add(key);renderProgress();}
function renderTabs(){document.getElementById('serviceTabs').innerHTML=services.map(s=>`<button class="service-tab ${state.svc===s?'active':''}" onclick="state.svc='${s}';render()">${s}</button>`).join('')}
function renderProgress(){const d=state.done[state.svc].size,t=tasks[state.svc].length;document.getElementById('doneCount').textContent=d;document.getElementById('totalCount').textContent=t;document.getElementById('taskText').textContent=d>=t?'体験完了。下部の実サービスで同じ操作を試してください。':tasks[state.svc][d];}
function appbar(title,color='var(--blue)'){return `<div class="appbar" style="background:${color}"><div class="title">${title}</div><div class="actions"><span>自動保存</span><span>共有</span><span>コメント</span></div></div>`}
function word(){const w=state.word;const tabs=['ファイル','ホーム','挿入','レイアウト','デザイン','校閲','表示','差し込み文書'];let ribbon=''; if(state.wordTab==='ホーム')ribbon=`<button class="btn ${w.bold?'active':''}" onclick="state.word.bold=!state.word.bold;mark('bold');render()">太字</button><button class="btn ${w.underline?'active':''}" onclick="state.word.underline=!state.word.underline;mark('underline');render()">下線</button><button class="btn ${w.bullets?'active':''}" onclick="state.word.bullets=!state.word.bullets;mark('bullets');render()">箇条書き</button><span class="sep"></span><label>スタイル</label><select class="select" onchange="state.word.style=this.value;mark('style');render()"><option ${w.style==='標準'?'selected':''}>標準</option><option ${w.style==='見出し'?'selected':''}>見出し</option><option ${w.style==='強調'?'selected':''}>強調</option></select>`; if(state.wordTab==='挿入')ribbon=`<button class="btn" onclick="state.word.table=true;mark('table');render()">3×3 表を挿入</button><button class="btn" onclick="insertText('リンク: https://www.microsoft365.com');mark('link');render()">リンク</button>`; if(state.wordTab==='レイアウト')ribbon=`<label>余白</label><select class="select" onchange="state.word.margin=this.value;mark('margin');render()"><option>標準</option><option>狭い</option><option>広い</option></select>`; if(state.wordTab==='デザイン')ribbon=`<button class="btn" onclick="state.word.bg=state.word.bg==='#fff'?'#fff8d7':'#fff';mark('bg');render()">ページ背景</button><button class="btn ${w.border?'active':''}" onclick="state.word.border=!state.word.border;mark('border');render()">ページ罫線</button>`; if(state.wordTab==='校閲')ribbon=`<button class="btn" onclick="state.word.comments++;mark('comment');render()">コメントを追加</button>`; if(state.wordTab==='表示')ribbon=`<button class="btn" onclick="state.word.zoom='90%';mark('zoom');render()">90%</button><button class="btn" onclick="state.word.zoom='100%';mark('zoom');render()">100%</button><button class="btn" onclick="state.word.zoom='110%';mark('zoom');render()">110%</button>`; if(state.wordTab==='差し込み文書')ribbon=`<button class="btn" onclick="insertText('《氏名》 様');state.word.mail=true;mark('mail');render()">差し込みフィールド</button>`; if(state.wordTab==='ファイル')ribbon=`<button class="btn" onclick="state.word.saved='OneDrive - 個人';mark('save');render()">OneDriveに保存</button><button class="btn" onclick="state.word.share='指定したユーザー';mark('share');render()">共有</button>`;
let style=`font-weight:${w.bold?'700':'400'};text-decoration:${w.underline?'underline':'none'};background:${w.bg};border:${w.border?'4px double #6b8fc9':'1px solid #d3d6dc'};`; let content=w.text; if(w.bullets) content += '<ul><li>OneDriveは個人作業用</li><li>SharePointはチーム共有用</li><li>Teamsから関係者へ共有</li></ul>'; if(w.table) content += '<table style="width:100%;border-collapse:collapse;margin-top:12px"><tr><th style="border:1px solid #999">保存先</th><th style="border:1px solid #999">用途</th><th style="border:1px solid #999">共有</th></tr><tr><td style="border:1px solid #999">OneDrive</td><td style="border:1px solid #999">個人作業</td><td style="border:1px solid #999">限定共有</td></tr><tr><td style="border:1px solid #999">SharePoint</td><td style="border:1px solid #999">チーム管理</td><td style="border:1px solid #999">組織共有</td></tr></table>';return `${appbar('Word　保存ルール.docx')}<div class="tabs">${tabs.map(t=>`<div class="tab ${state.wordTab===t?'active':''}" onclick="state.wordTab='${t}';render()">${t}</div>`).join('')}</div><div class="ribbon">${ribbon}</div><div class="work"><div class="page" contenteditable="true" oninput="state.word.text=this.innerHTML;mark('edit')" style="${style}">${content}</div><div class="status-card"><h3>文書の状態</h3><div class="row"><span>保存先</span><b>${w.saved}</b></div><div class="row"><span>共有</span><b>${w.share}</b></div><div class="row"><span>表示</span><b>${w.zoom}</b></div><div class="row"><span>コメント</span><b>${w.comments}件</b></div><div class="note">白紙ページを直接編集し、リボン操作の結果がこの画面に反映されます。</div></div></div><div class="footer"><span>ページ 1/1</span><span>表示 ${w.zoom} ・ 余白 ${w.margin} ・ スタイル ${w.style}</span></div>`}
function insertText(t){state.word.text += `<p>${t}</p>`}
function excel(){const e=state.excel;return `${appbar('Excel　売上一覧.xlsx','#217346')}<div class="tabs"><div class="tab active">ホーム</div><div class="tab">挿入</div><div class="tab">数式</div><div class="tab">表示</div></div><div class="ribbon"><button class="btn" onclick="state.excel.selected='B5';mark('select');render()">合計セルを選択</button><input class="input" value="${e.formula}" onchange="state.excel.formula=this.value;mark('formula')"><button class="btn" onclick="calc();mark('calc');render()">計算</button><button class="btn" onclick="state.excel.chart=true;mark('chart');render()">グラフ</button><button class="btn ${e.protected?'active':''}" onclick="state.excel.protected=!state.excel.protected;mark('protect');render()">保護</button></div><div class="formula"><span class="fx">fx</span><span>${e.formula}</span></div><div class="work" style="grid-template-columns:1fr 310px"><div><div class="grid grid4"><div class="head"></div><div class="head">A</div><div class="head">B</div><div class="head">C</div><div class="head">D</div><div class="head">1</div><div class="cell">部署</div><div class="cell">売上</div><div class="cell">件数</div><div class="cell">備考</div><div class="head">2</div><div class="cell">総務</div><div class="cell">120</div><div class="cell">6</div><div class="cell">通常</div><div class="head">3</div><div class="cell">医事</div><div class="cell">230</div><div class="cell">8</div><div class="cell">増加</div><div class="head">4</div><div class="cell">看護</div><div class="cell">180</div><div class="cell">7</div><div class="cell">通常</div><div class="head">5</div><div class="cell">合計</div><div class="cell sel">${e.result}</div><div class="cell"></div><div class="cell"></div></div>${e.chart?'<div class="chart"><div class="bar" style="height:70px"></div><div class="bar" style="height:126px"></div><div class="bar" style="height:96px"></div></div>':''}</div><div class="status-card"><h3>ブックの状態</h3><div class="row"><span>選択セル</span><b>${e.selected}</b></div><div class="row"><span>数式</span><b>${e.formula}</b></div><div class="row"><span>計算結果</span><b>${e.result}</b></div><div class="row"><span>保護</span><b>${e.protected?'有効':'無効'}</b></div><div class="note">F3のExcel for the webでも、SUMなどの基本数式を体験する想定です。</div></div></div><div class="footer"><span>Sheet1</span><span>表示 100%</span></div>`}
function calc(){const f=state.excel.formula.toUpperCase(); if(f.includes('SUM'))state.excel.result=530; else if(f.includes('AVERAGE'))state.excel.result=177; else if(f.includes('MAX'))state.excel.result=230; else state.excel.result='式を確認'}
function teams(){const t=state.teams;return `${appbar('Teams　総務部チャネル', 'var(--purple)')}<div class="ribbon"><button class="btn" onclick="state.teams.mention=true;state.teams.sent=true;mark('mention');render()">@佐藤 さんへ送信</button><button class="btn" onclick="state.teams.file=true;mark('file');render()">ファイル共有</button><button class="btn" onclick="state.teams.reaction=true;mark('reaction');render()">リアクション</button><button class="btn" onclick="state.teams.meeting=true;mark('meeting');render()">会議開始</button></div><div class="team-layout"><div class="rail"><b>チーム</b><div class="channel active">一般</div><div class="channel">研修</div><div class="channel">ファイル共有</div></div><div class="chat"><div class="message"><b>田中</b><br>本日の資料を確認してください。</div>${t.mention?'<div class="message"><b>あなた</b><br>@佐藤 保存ルールの確認をお願いします。</div>':''}${t.file?'<div class="message"><b>あなた</b><br>ファイルを共有しました: 保存ルール.docx</div>':''}${t.reaction?'<div class="message">田中の投稿に「いいね」を付けました。</div>':''}<div class="compose"><input class="input" style="flex:1" value="@佐藤 確認お願いします"><button class="btn">送信</button></div></div><div class="side"><h3>状態</h3><div class="row"><span>@メンション</span><b>${t.mention?'済':'未'}</b></div><div class="row"><span>共有ファイル</span><b>${t.file?'1件':'0件'}</b></div><div class="row"><span>会議</span><b>${t.meeting?'開始中':'未開始'}</b></div><div class="note">@メンションで相手に通知し、チャネル内で資料共有します。</div></div></div>`}
function od(){const o=state.od;const files=['研修資料.docx','売上一覧.xlsx','共有フォルダー'];return `${appbar('OneDrive　自分のファイル')}<div class="ribbon"><button class="btn" onclick="state.od.uploaded=true;mark('upload');render()">アップロード</button><button class="btn" onclick="state.od.shared=true;mark('share');render()">共有リンク</button><button class="btn" onclick="state.od.sync='同期中 → 同期済み';mark('sync');render()">同期確認</button><button class="btn" onclick="state.od.version='1つ前を復元';mark('restore');render()">復元</button></div><div class="file-list"><div class="leftnav"><b>OneDrive</b><div class="channel active">自分のファイル</div><div class="channel">共有</div><div class="channel">ごみ箱</div></div><div class="mainlist">${files.concat(o.uploaded?['アップロード資料.pdf']:[]).map(f=>`<div class="file-row ${o.selected===f?'active':''}" onclick="state.od.selected='${f}';mark('select');render()"><span>${f}</span><span>${f.includes('フォルダー')?'フォルダー':'ファイル'}</span><span>${o.shared&&f===o.selected?'共有中':'非共有'}</span></div>`).join('')}</div><div class="details"><h3>詳細</h3><div class="row"><span>選択</span><b>${o.selected}</b></div><div class="row"><span>同期</span><b>${o.sync}</b></div><div class="row"><span>共有</span><b>${o.shared?'リンク作成済':'未共有'}</b></div><div class="row"><span>版</span><b>${o.version}</b></div><div class="note">アップロード後、一覧にファイルが追加され、共有や復元の状態が変わります。</div></div></div>`}
function sp(){const s=state.sp;return `${appbar('SharePoint　チームサイト','var(--teal)')}<div class="ribbon"><select class="select" onchange="state.sp.site=this.value;mark('site');render()"><option>総務部サイト</option><option>医事課サイト</option><option>看護部サイト</option></select><button class="btn" onclick="state.sp.added=true;mark('add');render()">ドキュメント追加</button><button class="btn" onclick="state.sp.perm=true;mark('perm');render()">権限確認</button><button class="btn" onclick="state.sp.news=true;mark('news');render()">ニュース投稿</button></div><div class="file-list"><div class="leftnav"><b>${s.site}</b><div class="channel active">ドキュメント</div><div class="channel">ニュース</div><div class="channel">サイトの権限</div></div><div class="mainlist"><div class="site-top"><button class="btn">新規</button><button class="btn">アップロード</button><button class="btn">共有</button></div>${['研修資料.docx','売上一覧.xlsx','議事録.docx'].concat(s.added?['追加資料.pptx']:[]).map(f=>`<div class="file-row"><span>${f}</span><span>更新済み</span><span>${s.perm?'閲覧可':'標準'}</span></div>`).join('')}${s.news?'<div class="news"><b>ニュース</b><br>Microsoft 365研修のお知らせを投稿しました。</div>':''}</div><div class="details"><h3>サイト情報</h3><div class="row"><span>サイト</span><b>${s.site}</b></div><div class="row"><span>追加</span><b>${s.added?'1件':'0件'}</b></div><div class="row"><span>権限</span><b>${s.perm?'確認済':'未確認'}</b></div><div class="row"><span>ニュース</span><b>${s.news?'投稿済':'未投稿'}</b></div><div class="note">SharePointはチームの文書置き場として、権限管理とニュース発信も行えます。</div></div></div>`}
function cop(){const c=state.cop;return `${appbar('Copilot　基本操作')}<div class="ribbon"><button class="btn" onclick="state.cop.prompt='研修資料の要点を3つに要約してください。';mark('prompt');render()">要約例</button><button class="btn" onclick="state.cop.prompt='職員向けのお知らせ文を丁寧に整えてください。';mark('prompt');render()">文章整理例</button><button class="btn" onclick="state.cop.prompt='次に確認すべき操作を提案してください。';mark('prompt');render()">操作提案例</button></div><div class="copilot"><div class="prompt"><h3>プロンプト</h3><textarea class="textarea" oninput="state.cop.prompt=this.value;mark('input')">${c.prompt}</textarea><br><br><button class="btn" onclick="makeCopilot();mark('run');render()">実行</button><button class="btn" onclick="state.cop.answer='文章を読みやすく整え、箇条書きにしました。';mark('clean');render()">文章を整える</button><button class="btn" onclick="state.cop.answer='次は、共有範囲、保存先、権限設定を確認しましょう。';mark('next');render()">次の操作</button></div><div class="answer"><h3>Copilotの回答</h3><p>${c.answer}</p><div class="note">プロンプトを変えると、回答の方向性も変わることを確認します。</div></div></div>`}
function makeCopilot(){state.cop.answer=`入力内容「${state.cop.prompt}」をもとに、要点を整理しました。1. 目的を明確にする 2. 関係者へ共有する 3. 保存先をOneDriveまたはSharePointに分ける`;}
function render(){renderTabs();renderProgress();const m={Word:word,Excel:excel,Teams:teams,OneDrive:od,SharePoint:sp,Copilot:cop};document.getElementById('shell').innerHTML=m[state.svc]();renderProgress();}
render();
</script>
</body>
</html>
'''

components.html(APP_HTML, height=760, scrolling=False)
