import streamlit as st
import streamlit.components.v1 as components
from modules.ui import load_css, page_header
from modules.urls import M365_URLS

st.set_page_config(page_title="Excel Training", page_icon="📊", layout="wide")
load_css()
page_header("Excel：セル編集・集計・グラフ", "リボン操作を使い、セル編集から分析までを順番に体験します。")
excel_url = M365_URLS["Excel"]
html = f"""
<!doctype html><html><head><meta charset='utf-8'><style>
body{{margin:0;font-family:'Segoe UI','Yu Gothic',Meiryo,sans-serif;background:#eef3f8;color:#1f2937}} .shell{{border:1px solid #cbd5e1;border-radius:20px;background:white;overflow:hidden;box-shadow:0 14px 35px #0002}} .top{{background:#217346;color:white;padding:12px 16px;font-weight:800}} .task{{background:#ecfdf3;border-bottom:1px solid #b7e4c7;padding:12px 16px;font-weight:800;color:#14532d}} .tabs{{display:flex;gap:4px;background:#f8fafc;border-bottom:1px solid #cbd5e1;padding:8px 12px 0}} .tab{{border:0;background:transparent;padding:10px 16px;border-radius:8px 8px 0 0;font-weight:700;cursor:pointer}} .tab.active{{background:white;border:1px solid #cbd5e1;border-bottom:white;color:#217346}} .ribbon{{display:flex;gap:8px;flex-wrap:wrap;padding:12px;border-bottom:1px solid #cbd5e1;min-height:72px}} .btn{{border:1px solid #b8c6d8;background:#fff;border-radius:8px;padding:8px 10px;font-weight:700;cursor:pointer}} .gridwrap{{display:grid;grid-template-columns:1fr 310px;gap:16px;padding:18px;background:#e9edf5}} table{{border-collapse:collapse;background:white}} th{{background:#eef2f7;color:#475569;font-size:12px}} td,th{{border:1px solid #cbd5e1;width:110px;height:34px;text-align:left;padding:5px}} td{{cursor:text}} td.sel{{outline:3px solid #217346;outline-offset:-3px}} .side{{background:#fff;border:1px solid #cbd5e1;border-radius:16px;padding:14px}} .done{{color:#15803d;font-weight:800}} .cta{{display:none;background:#ecfdf3;border:1px solid #86efac;border-radius:14px;padding:14px;margin-top:14px}} .cta a{{display:block;background:#217346;color:white;padding:10px;border-radius:10px;text-align:center;text-decoration:none;font-weight:800;margin-top:10px}} #chart{{height:160px;display:flex;align-items:end;gap:10px;margin-top:12px;padding:12px;background:#f8fafc;border:1px solid #dbe4f0;border-radius:12px}} .bar{{width:42px;background:#217346;border-radius:6px 6px 0 0}}
</style></head><body><div class='shell'><div class='top'>Excel - 売上管理.xlsx</div><div class='task' id='task'>体験 1/5：セルを選択し、太字または塗りつぶしを押してください。</div><div class='tabs' id='tabs'></div><div class='ribbon' id='ribbon'></div><div class='gridwrap'><div><table id='sheet'></table><div id='chart'></div></div><div class='side'><h3>体験チェック</h3><div id='checks'></div><div class='cta' id='cta'><b>体験完了です。</b><br>次は実際のExcel for the webで操作してください。<a href='{excel_url}' target='_blank'>実体験をしてください：Excelを開く ↗</a><small>{excel_url}</small></div></div></div></div>
<script>
const tabs=['ホーム','挿入','ページレイアウト','数式','データ','校閲','表示']; let active='ホーム'; let selected=null; const done={{format:false,sum:false,chart:false,protect:false,view:false}};
const rows=[['','A','B','C','D'],['1','部門','4月','5月','合計'],['2','総務','120','135',''],['3','医事','180','210',''],['4','看護','260','280','']];
function drawSheet(){{let h=''; rows.forEach((r,i)=>{{h+='<tr>'+r.map((c,j)=>i==0||j==0?`<th>${{c}}</th>`:`<td contenteditable onclick="sel(this)">${{c}}</td>`).join('')+'</tr>'}}); document.getElementById('sheet').innerHTML=h;}}
function sel(td){{document.querySelectorAll('td').forEach(x=>x.classList.remove('sel'));td.classList.add('sel');selected=td;}}
function tab(t){{active=t;drawTabs();drawRibbon();}}
function drawTabs(){{document.getElementById('tabs').innerHTML=tabs.map(t=>`<button class='tab ${{t==active?'active':''}}' onclick="tab('${{t}}')">${{t}}</button>`).join('')}}
function drawRibbon(){{let r=''; if(active==='ホーム')r=`<button class='btn' onclick='fmt("bold")'>太字</button><button class='btn' onclick='fmt("underline")'>下線</button><button class='btn' onclick='fill()'>塗りつぶし</button><button class='btn' onclick='border()'>罫線</button>`; if(active==='挿入')r=`<button class='btn' onclick='makeChart()'>グラフ</button><button class='btn' onclick='addRow()'>行挿入</button>`; if(active==='数式')r=`<button class='btn' onclick='sum()'>合計</button><button class='btn' onclick='formula()'>数式表示</button>`; if(active==='データ')r=`<button class='btn' onclick='sortRows()'>並べ替え</button><button class='btn' onclick='filter()'>フィルター</button>`; if(active==='校閲')r=`<button class='btn' onclick='protect()'>シート保護</button><button class='btn' onclick='comment()'>コメント</button>`; if(active==='表示')r=`<button class='btn' onclick='zoom(90)'>90%</button><button class='btn' onclick='zoom(100)'>100%</button><button class='btn' onclick='zoom(120)'>120%</button>`; if(active==='ページレイアウト')r=`<button class='btn' onclick='document.body.style.background="#e5f1ea"'>テーマ</button><button class='btn' onclick='done.format=true;update()'>印刷範囲</button>`; document.getElementById('ribbon').innerHTML=r;}}
function fmt(p){{if(selected)selected.style[p]='700';done.format=true;update()}} function fill(){{if(selected)selected.style.background='#d9ead3';done.format=true;update()}} function border(){{if(selected)selected.style.border='3px solid #217346';done.format=true;update()}}
function sum(){{document.querySelectorAll('td')[3].textContent='255';document.querySelectorAll('td')[7].textContent='390';document.querySelectorAll('td')[11].textContent='540';done.sum=true;update()}} function formula(){{alert('=SUM(B2:C2) のように範囲を指定します。')}}
function makeChart(){{document.getElementById('chart').innerHTML='<div class=bar style="height:70px"></div><div class=bar style="height:100px"></div><div class=bar style="height:135px"></div>';done.chart=true;update()}} function addRow(){{let tr=document.createElement('tr');tr.innerHTML='<th>5</th><td contenteditable onclick="sel(this)">薬剤</td><td contenteditable onclick="sel(this)">90</td><td contenteditable onclick="sel(this)">100</td><td contenteditable onclick="sel(this)"></td>';document.getElementById('sheet').appendChild(tr);done.chart=true;update()}}
function protect(){{document.querySelectorAll('td').forEach(td=>td.contentEditable=false);done.protect=true;update()}} function comment(){{if(selected)selected.title='確認してください';done.protect=true;update()}}
function zoom(v){{document.getElementById('sheet').style.transform=`scale(${{v/100}})`;document.getElementById('sheet').style.transformOrigin='top left';done.view=true;update()}} function sortRows(){{done.sum=true;update()}} function filter(){{done.sum=true;update()}}
function update(){{const labels={{format:'セル書式を変更',sum:'合計を計算',chart:'グラフまたは行を追加',protect:'校閲機能を使用',view:'表示倍率を変更'}}; document.getElementById('checks').innerHTML=Object.keys(done).map(k=>`<div class='${{done[k]?'done':''}}'>${{done[k]?'✓':'○'}} ${{labels[k]}}</div>`).join(''); let next=Object.keys(done).find(k=>!done[k]); document.getElementById('task').textContent=next?'体験：'+labels[next]+'してください。':'体験完了：実体験URLからExcelを開いてください。'; if(!next)document.getElementById('cta').style.display='block';}}
drawSheet();drawTabs();drawRibbon();update();
</script></body></html>
"""
components.html(html, height=840, scrolling=True)
